"""empty message

Revision ID: 32bb63a92e15
Revises: dbb5e36bf239
Create Date: 2021-12-03 02:55:36.651886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bb63a92e15'
down_revision = 'dbb5e36bf239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('trx_ipaddress', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'trx_ipaddress')
    # ### end Alembic commands ###
