"""empty message

Revision ID: dbb5e36bf239
Revises: 
Create Date: 2021-12-03 02:47:18.015498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbb5e36bf239'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_state',
    sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('state_name', mysql.VARCHAR(length=20), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('state_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
